Reservas/Controllers/MesasController.cs
using Microsoft.AspNetCore.Mvc;
using Reservas.Models;
using Reservas.Interfaces;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;

namespace Reservas.Controllers
{
    public class MesasController : Controller
    {

        private readonly IMesa mesaInterface;

        public MesasController(IMesa mesaInterface)
        {
            this.mesaInterface = mesaInterface;
        }

        [HttpGet]
        public IActionResult Index()
        {
            var listaMesas = mesaInterface.getLista();
            return View(listaMesas);
        }


        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Mesa mesa)
        {
            if (ModelState.IsValid)
            {
                mesaInterface.createMesa(mesa);
                TempData["mensaje"] = "La mesa se ha creado correctamente";
                return RedirectToAction("Index");
            }

            return View();
        }


        public IActionResult Edit(int? id)
        {
            var mesa = mesaInterface.getMesa(id);
            return View(mesa);
        }


        [HttpPost]
        public IActionResult Edit(Mesa mesa)
        {
            if (ModelState.IsValid)
            {
                mesaInterface.updateMesa(mesa);

                TempData["mensaje"] = "La mesa se ha editado correctamente";
                return RedirectToAction("Index");
            }

            return View();
        }


        public IActionResult Delete(int? id)
        {
            var mesa = mesaInterface.getMesa(id);
            return View(mesa);
        }


        [HttpPost]
        public IActionResult DeleteMesa(int? id)
        {
            mesaInterface.deleteMesa(id);

            TempData["mensaje"] = "La mesa se ha eliminado correctamente";
            return RedirectToAction("Index");

        }
    }
}

Reservas/Controllers/PlatosController.cs
using Microsoft.AspNetCore.Mvc;
using Reservas.Interface;
using Reservas.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Reservas.Controllers
{
    public class PlatosController : Controller
    {
        private readonly IPlato platosInterface;
        private readonly ICategoria categoriasInterface;

        public PlatosController(IPlato platosInterface, ICategoria categoriasInterface)
        {
            this.platosInterface = platosInterface;
            this.categoriasInterface = categoriasInterface;
        }

        public IActionResult Index()
        {
            var listaPlatos = platosInterface.getLista();
            return View(listaPlatos);
        }

        public IActionResult Create()
        {
            ViewBag.Categoria = categoriasInterface.getLista();
            return View();
        }


        [HttpPost]
        public IActionResult Create(Plato plato)
        {
            if (ModelState.IsValid)
            {
                platosInterface.createPlato(plato);
                TempData["mensaje"] = "El plato se ha creado correctamente";
                return RedirectToAction("Index");
            }

            return View();
        }

        public IActionResult Edit(int? id)
        {
            var plato = platosInterface.getPlato(id);
            ViewBag.Categoria = categoriasInterface.getLista();
            return View(plato);
        }


        [HttpPost]
        public IActionResult Edit(Plato plato)
        {
            if (ModelState.IsValid)
            {
                platosInterface.updatePlato(plato);
                TempData["mensaje"] = "El plato se ha editado correctamente";
                return RedirectToAction("Index");
            }

            return View();
        }


        public IActionResult Delete(int? id)
        {
            var plato = platosInterface.getPlato(id);
            return View(plato);
        }


        [HttpPost]
        public IActionResult DeletePlato(int? id)
        {
            platosInterface.deletePlato(id);

            TempData["mensaje"] = "El plato se ha eliminado correctamente";
            return RedirectToAction("Index");

        }
    }
}

Reservas/Controllers/ReservaController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Reservas.Interfaces;
using Reservas.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Reservas.Controllers
{
    public class ReservaController : Controller
    {
        private readonly IReserva reservasInterface;
        private readonly IMesa mesasInterface;


        public ReservaController(IReserva reservaInterface, IMesa mesasInterface)
        {
            this.reservasInterface = reservaInterface;
            this.mesasInterface = mesasInterface;
        }

        public IActionResult Index(string? criterio)
        {
            var listaMesas = reservasInterface.getLista(criterio);
            return View(listaMesas);
        }


        
        public IActionResult Create()
        {
            ViewBag.Mesa = mesasInterface.getMesaByState();
            return View();
        }

        
        [HttpPost]
        public IActionResult Create(Reserva reserva)
        {
            if (ModelState.IsValid)
            {
                reservasInterface.createReserva(reserva);
                TempData["mensaje"] = "La reserva se ha creado correctamente";
                return RedirectToAction("Index");
            }

            return View();
        }

        
        public IActionResult Edit(int? id)
        {
            var reserva = reservasInterface.getReserva(id);
            ViewBag.Mesa = mesasInterface.getMesaByState();
            return View(reserva);
        }

        
        [HttpPost]
        public IActionResult Edit(Reserva reserva, int idR)
        {
            if (ModelState.IsValid)
            {
                reservasInterface.updateReserva(reserva, idR);
                TempData["mensaje"] = "La reserva se ha editado correctamente";
                return RedirectToAction("Index");
            }

            return View();
        }

        
        public IActionResult Delete(int? id)
        {
            var reserva = reservasInterface.getReserva(id);
            return View(reserva);
        }

        
        [HttpPost]
        public IActionResult DeleteReserva(int? id)
        {
            reservasInterface.deleteReserva(id);

            TempData["mensaje"] = "La reserva se ha eliminado correctamente";
            return RedirectToAction("Index");

        }

    }
}

Reservas/Controllers/UsuariosController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Reservas.Interfaces;
using Reservas.Models;

namespace Reservas.Controllers
{
    public class UsuariosController : Controller
    {

        protected readonly IPersonal IPersonal;

        public UsuariosController(IPersonal IPersonal)
        {
            this.IPersonal = IPersonal;
        }

        [HttpGet]
        public IActionResult Index()
        {
            var listaPersonal = IPersonal.getLista();
            return View(listaPersonal);
        }


        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Personal personal)
        {
            if (ModelState.IsValid)
            {
                IPersonal.createPersonal(personal);
                TempData["mensaje"] = "El usuario se ha creado correctamente";
                return RedirectToAction("Index");
            }
            return View();
        }


        public IActionResult Edit(int? id)
        {
            var peronal = IPersonal.getPersonal(id);
            return View(peronal);
        }

        [HttpPost]
        public IActionResult Edit(Personal personal)
        {
            if (ModelState.IsValid)
            {
                IPersonal.updatePersonal(personal);

                TempData["mensaje"] = "El usuario se ha editado correctamente";
                return RedirectToAction("Index");
            }

            return View();
        }


        public IActionResult Delete(int? id)
        {
            var personal = IPersonal.getPersonal(id);
            return View(personal);
        }

        [HttpPost]
        public IActionResult DeleteMesa(int? id)
        {
            IPersonal.deletePersona(id);
            TempData["mensaje"] = "El usuario se ha eliminado correctamente";
            return RedirectToAction("Index");

        }
    }
}

Reservas/Views/Shared/_AuthLayout.cshtml
@{
    Layout = "/Views/Shared/_LayoutRes.cshtml";

}

<div class="row">
    <div class="col-md-6 offset-md-3">
        <div class="card login-logout-tab">
            <div class="card-header">
                <ul class="nav nav-tabs card-header-tabs">
                    <li class="nav-item">
                        <a class="nav-link" href="/Auth/Login">Sign In</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" href="/Auth/Register">Sign Up</a>
                    </li>
                </ul>
            </div>
            <div class="card-content">

                <div class="col-md-12">
                    @RenderBody()
                </div>


            </div>
        </div>
    </div>
</div>

@section Scripts{
    @RenderSection("Scripts", required: false)

    <script>
        $(function () {
            var current = location.pathname;
            $('.nav-tabs li a').each(function () {
                var $this = $(this);
                if (current.indexOf($this.attr('href')) !== -1) {
                    $this.addClass('active');
                }
            })
        })
    </script>
}

Reservas/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Reservas</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet">
    <script src="https://kit.fontawesome.com/e745eea8c3.js" crossorigin="anonymous"></script>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container">
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2021 - Reservas - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@RenderSection("Scripts", required: false)
</body>
</html>

Reservas/Views/Shared/_LayoutHome.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Reservas</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet">
    <script src="https://kit.fontawesome.com/e745eea8c3.js" crossorigin="anonymous"></script>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container">
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2021 - Reservas - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@RenderSection("Scripts", required: false)
</body>
</html>

Reservas/Views/Shared/_LayoutRes.cshtml
@{
    ViewBag.Title = "Index";
    Layout = null;
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Reservas</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet">
    <script src="https://kit.fontawesome.com/e745eea8c3.js" crossorigin="anonymous"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" id="goReservas" asp-controller="Reserva" asp-action="Index">Reservas</a>

                <a class="navbar-brand" asp-area="" id="goMesas" asp-controller="Mesas" asp-action="Index">Mesas</a>
                <a class="navbar-brand" asp-area="" id="goUsuarios" asp-controller="Usuarios" asp-action="Index">Usuarios</a>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">


                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item dropdown">
                            <a class="navbar-brand dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-expanded="false">
                                Menú
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" id="goPlatos" asp-controller="Platos" asp-action="Index">Platos</a>
                                <a class="dropdown-item" id="goCategorias" asp-controller="Categorias" asp-action="Index">Categorías</a>
                            </div>
                        </li>
                    </ul>
                </div>
                   
                    <div id="logout" class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                        <a class="navbar-brand" asp-area="" id="goMesas" asp-controller="Auth" asp-action="Logout">Logout</a>
                    </div>
                </div>
</nav>
    </header>


    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>

    </div>


    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Reservas - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>