Reservas/Controllers/CategoriasController.cs
using Microsoft.AspNetCore.Mvc;
using Reservas.Interface;
using Reservas.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Reservas.Controllers
{
    public class CategoriasController : Controller
    {
        private readonly ICategoria categoriaInterface;

        public CategoriasController(ICategoria categoriaInterface)
        {
            this.categoriaInterface = categoriaInterface;
        }

        [HttpGet]
        public IActionResult Index()
        {
            var listaCategorias = categoriaInterface.getLista();
            return View(listaCategorias);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(CategoriaPlato categoriaPlato)
        {
            if (ModelState.IsValid)
            {
                categoriaInterface.createCategoriaPlato(categoriaPlato);
                TempData["mensaje"] = "La categoria se ha creado correctamente";
                return RedirectToAction("Index");
            }

            return View();
        }

        public IActionResult Edit(int? id)
        {
            var categoria = categoriaInterface.getCategoria(id);
            return View(categoria);
        }


        [HttpPost]
        public IActionResult Edit(CategoriaPlato categoriaPlato)
        {
            if (ModelState.IsValid)
            {
                categoriaInterface.updateCategoria(categoriaPlato);

                TempData["mensaje"] = "La categoria se ha editado correctamente";
                return RedirectToAction("Index");
            }

            return View();
        }

        public IActionResult Delete(int? id)
        {
            var categoria = categoriaInterface.getCategoria(id);
            return View(categoria);
        }


        [HttpPost]
        public IActionResult DeleteCategoria(int? id)
        {
            categoriaInterface.deleteCategoria(id);

            TempData["mensaje"] = "La categoría se ha eliminado correctamente";
            return RedirectToAction("Index");
        }

    }
}

Reservas/Views/Categorias/Create.cshtml
@model Reservas.Models.CategoriaPlato
@{
    ViewData["Title"] = "Crear Nueva Categoría";
    Layout = "/Views/Shared/_LayoutRes.cshtml";
}

<div class="container">
    <div class="row">
        <div class="col-sm-12">
            <h3>Crear Nueva Categoría</h3>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-10">
            <div class="card">
                <div class="card-body">

                    <form method="post" asp-action="Create">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <div class="form-group">
                            <label asp-for="NombreCategoria" class="control-label"> Nombre Categoría</label>
                            <input id="NombreCategoria" asp-for="NombreCategoria" class="form-control" />
                            <span asp-validation-for="NombreCategoria" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <input type="submit" id="crearMesa" value="Crear Categoria" class="btn btn-primary" />
                        </div>
                    </form>
                </div>

            </div>
        </div>
    </div>
</div>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

Reservas/Views/Categorias/Delete.cshtml
@model Reservas.Models.CategoriaPlato


@{
    ViewData["Title"] = "Eliminar Categoría";
    Layout = "/Views/Shared/_LayoutRes.cshtml";
}

<div class="container">
    <div class="row">
        <div class="col-sm-12">
            <h3>Eliminar Categoría</h3>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-10">
            <div class="card">
                <div class="card-body">
                    <form method="post" asp-action="DeleteCategoria">
                        <input type="hidden" asp-for="Id" />

                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <div class="form-group">
                            <label asp-for="NombreCategoria" class="control-label">Nombre Categoría</label>
                            <input asp-for="NombreCategoria" id="NombreCategoria" class="form-control" disabled />
                            <span asp-validation-for="NombreCategoria" class="text-danger"></span>
                        </div>


                        <div class="form-group">
                            <input type="submit" id="eliminarCategoria" value="Eliminar Categoría" class="btn btn-primary" />
                        </div>
                    </form>
                </div>

            </div>
        </div>
    </div>
</div>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

Reservas/Views/Categorias/Edit.cshtml
@model Reservas.Models.CategoriaPlato


@{
    ViewData["Title"] = "Editar Categoría";
    Layout = "/Views/Shared/_LayoutRes.cshtml";
}

<div class="container">
    <div class="row">
        <div class="col-sm-12">
            <h3>Editar Categoria</h3>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-10">
            <div class="card">
                <div class="card-body">
                    <form method="post" asp-action="Edit">
                        <input type="hidden" asp-for="Id" />

                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <div class="form-group">
                            <label asp-for="NombreCategoria" class="control-label">Nombre Categoría</label>
                            <input asp-for="NombreCategoria" id="NombreCategoria" class="form-control" />
                            <span asp-validation-for="NombreCategoria" class="text-danger"></span>
                        </div>


                        <div class="form-group">
                            <input type="submit" id="editarCategoria" value="Editar Categoria" class="btn btn-primary" />
                        </div>
                    </form>
                </div>

            </div>
        </div>
    </div>
</div>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

Reservas/Views/Categorias/Index.cshtml
@model IEnumerable<Reservas.Models.CategoriaPlato>

@{
    ViewData["Title"] = "Lista de Categorías";
    Layout = "/Views/Shared/_LayoutRes.cshtml";
}

<div class="container">

    @if (TempData["mensaje"] != null)
    {
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
            @TempData["mensaje"]
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    }
    <div class="row">
        <div class="col-sm-6">
            <h3>Lista de Categorías</h3>
        </div>
        <div class="col-sm-6">
            <a class="btn btn-success d-block" id="agregarNuevaCategoria" asp-action="Create" asp-controller="Categorias">Agregar nueva categoria</a>
        </div>
    </div>

    <div class="row mt-3">
        @if (Model.Count() > 0)
        {
            <table class="table table-bordered table-striped">
                <thead>
                    <tr>
                        <td>ID</td>
                        <td>Nombre Categoría</td>
                        <td>Acciones</td>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                    <tr>
                        <td>@item.Id</td>
                        <td>@item.NombreCategoria</td>
                        <td>
                            <a asp-controller="Categorias" asp-action="Edit" id="editCategoria" asp-route-id="@item.Id" class="btn btn-warning">Editar</a>
                            <a asp-controller="Categorias" asp-action="Delete" id="deleteCategoria" asp-route-id="@item.Id" class="btn btn-danger">Eliminar</a>
                        </td>
                    </tr>
                    }
                </tbody>
            </table>
        }
        else
        {
            <p>No existen registros</p>
        }
    </div>

</div>